# Heroku recommended time-out setting
:timeout: 8

# Include mailers queue
:queues:
  - default
  - mailers

# Concurrency override based on redis-to-go plan in production environment
# NOTE: calculated with http://manuelvanrijn.nl/sidekiq-heroku-redis-calc/
production:
  :concurrency: 3
