if Rails.env.development?
  # coffees
  Array.new(50) do
    Coffee.create!(name: Faker::Coffee.blend_name,
                   origin: Faker::Coffee.origin,
                   producer: Faker::Name.name,
                   variety: Faker::Coffee.variety)
  end if Coffee.count.zero?

  # roasters
  Array.new(10) do
    Roaster.create!(name: Faker::Hipster.words(1)[0].capitalize + ' Roastery',
                    location: Faker::Address.city,
                    website: Faker::Internet.url)
  end if Roaster.count.zero?

  # users
  users =
    # let's make sure we have enough users for invites to make sense
    if User.count < 10
      Array.new(10) do
        User.create!(name: Faker::Name.name,
                     username: Faker::Internet.user_name,
                     email: Faker::Internet.email,
                     password: 'password',
                     password_confirmation: 'password')
      end
    else
      User.all.limit(10)
    end

  # only make past cuppings if no cuppings exist
  past_cuppings =
    if Cupping.count.zero?
      users.map.with_index do |user, idx|
        user.hosted_cuppings.create!(location: Faker::Address.street_address,
                                     cup_date: DateTime.now - idx,
                                     cups_per_sample: (2..5).to_a.sample) if idx.even?
      end
    else
      []
    end

  # always make new future cuppings
  future_cuppings = users.map.with_index do |user, idx|
    user.hosted_cuppings.create!(location: Faker::Address.street_address,
                                 cup_date: DateTime.now + idx,
                                 cups_per_sample: (2..5).to_a.sample) if idx.odd?
  end

  # to get rid of nil values
  [future_cuppings, past_cuppings].each do |cuppings|
    cuppings.select! { |cupping| !cupping.nil? }
  end

  # all cuppings
  cuppings = future_cuppings + past_cuppings

  # add cupped coffees to cuppings
  cuppings.each do |cupping|
    3.times do
      cupping.cupped_coffees.create!(roast_date: cupping.cup_date - 1,
                                     coffee_alias: "#{cupping.id}-#{Faker::Number.unique.number(3)}",
                                     coffee_id: Coffee.all.sample.id,
                                     roaster_id: Roaster.all.sample.id)
    end
  end

  # add invites to cuppings
  cuppings.each do |cupping|
    3.times do
      cupping.invites.create!(grader_id:
        if cupping.invites.empty?
          User.where('id != ?', cupping.host_id).sample.id
        else
          User.where('id != ? AND id NOT IN (?)', cupping.host_id,
                     cupping.invites.pluck(:grader_id))
                       .sample.id
        end)
    end
  end

  # add scores for each cupped coffee in past cuppings, then mark them as closed
  # (no scores added if only future cuppings are being generated by this seedfile)
  # NOTE FactoryGirl dependency in instantiating scores
  unless past_cuppings.empty?
    past_cuppings.each do |cupping|
      graders = User.find(cupping.invites.pluck(:grader_id))
      past_cupped_coffees = cupping.cupped_coffees
      # create scores for all combinations for graders/cupped coffees
      graders.product(past_cupped_coffees) do |p|
        p[1].scores.create!(FactoryGirl.attributes_for(:score,
                                                       grader_id: p[0].id,
                                                       cupping_id: cupping.id))
      end
      cupping.update(open: false)
    end
  end
end
